[package]
name = "cst-primitives"
version = "0.8.1"
authors = ["crustio"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[dependencies]
# third party dependencies
serde = { version = "1.0.106", optional = true, features = ["derive"] }
parity-scale-codec = { version = "1.3.4", default-features = false, features = ["bit-vec", "derive"] }

# substrate primitives
sp-runtime = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch",default-features = false }
sp-core = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-std = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
frame-support = { default-features = false,  git = "https://github.com/paritytech/substrate", branch = "rococo-branch"}

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-runtime/std",
	"sp-core/std",
	"sp-std/std",
	"frame-support/std",
	"serde",
]