[profile.release]
panic = 'unwind'

[patch.crates-io]
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-finality-tracker = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-offences = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-recovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-staking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-informant = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

[workspace]
members = [
    'cstrml/balances',
    'cstrml/staking',
    'cstrml/swork',
    'cstrml/market',
    'cstrml/payment',
    'runtime',
    'rpc',
    'node',
]