[package]
authors = ['crustio']
edition = '2018'
name = 'crust-rpc'
version = '0.11.0'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[dependencies]
jsonrpc-core = "15.1.0"
frame-rpc-system = { package = "substrate-frame-rpc-system", version = "2.0.1"  }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }

# substrate client dependencies
sc-client-api = "2.0.1"
sc-rpc = "2.0.1"
sc-consensus-babe  = "0.8.1"
sc-consensus-babe-rpc  = "0.8.1"
sc-consensus-epochs  = "0.8.1"
sc-finality-grandpa  = "0.8.1"
sc-finality-grandpa-rpc  = "0.8.1"
sc-keystore = "2.0.1"

# substrate pallet dependencies
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = "2.0.1"
sp-runtime = "2.0.1"
sp-api = "2.0.1"
sp-consensus  = "0.8.1"
sp-consensus-babe  = "0.8.1"
txpool-api = { package = "sp-transaction-pool", version = "2.0.1" }
pallet-transaction-payment-rpc = "2.0.1"
sp-block-builder = "2.0.1"

# crust dependent
crust-primitives = { version = "0.11.0", package = 'cst-primitives', path='../primitives' }
crust-runtime = { version = "0.11.0", package = 'crust-runtime', path = '../runtime' }
