[package]
name = "cstrml-balances"
version = "0.8.1"
authors = ["Crustio"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"}
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"}
frame-benchmarking = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false, optional = true }
frame-support = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
frame-system = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
primitives = { package = 'cst-primitives', path = '../../primitives', default-features = false }

[dev-dependencies]
sp-io = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch"}
sp-core = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch"}
pallet-transaction-payment = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch"}

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"primitives/std"
]
runtime-benchmarks = ["frame-benchmarking"]
