[package]
authors = ['crustio']
edition = '2018'
name = 'crust-runtime'
version = '0.11.0'
build = 'build.rs'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[build-dependencies]
substrate-wasm-builder = '3.0.0'

[dependencies]
# third party dependencies
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '1.3.5' }
serde = { features = ['derive'], optional = true, version = '1.0.117' }
static_assertions = "1.1.0"

# substrate primitives
authority-discovery-primitives = { default-features = false, package = 'sp-authority-discovery', version = "2.0.1" }
babe-primitives = { default-features = false, package = 'sp-consensus-babe', version = "0.8.1" }
sp-api = { default-features = false, version = "2.0.1" }
sp-block-builder = { default-features = false, version = "2.0.1" }
sp-core = { default-features = false, version = "2.0.1" }
sp-inherents = { default-features = false, version = "2.0.1" }
sp-io = { default-features = false, version = "2.0.1" }
sp-offchain = { default-features = false, version = "2.0.1" }
sp-runtime = { default-features = false, version = "2.0.1" }
sp-session = { default-features = false, version = "2.0.1" }
sp-staking = { default-features = false, version = "2.0.1" }
sp-std = { default-features = false, version = "2.0.1" }
sp-transaction-pool = { default-features = false, version = "2.0.1" }
sp-version = { default-features = false, version = "2.0.1" }

# substrate frame dependencies
pallet-authorship = { default-features = false, version = "2.0.1" }
pallet-authority-discovery = { default-features = false, version = "2.0.1" }
pallet-babe = { default-features = false, version = "2.0.1" }
pallet-bounties = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-collective = { default-features = false, version = "2.0.1" }
pallet-democracy = { default-features = false, version = "2.0.1" }
pallet-elections-phragmen = { default-features = false, version = "2.0.1" }
frame-executive = { default-features = false, version = "2.0.1" }
pallet-grandpa = { default-features = false, version = "2.0.1" }
pallet-im-online = { default-features = false, version = "2.0.1" }
pallet-indices = { version = "2.0.1", default-features = false }
pallet-identity = { default-features = false, version = "2.0.1"}
pallet-membership = { default-features = false, version = "2.0.1" }
pallet-offences = { default-features = false, version = "2.0.1" }
pallet-randomness-collective-flip = { default-features = false, version = "2.0.1" }
pallet-scheduler = { default-features = false, version = "2.0.1" }
pallet-session = { default-features = false, version = "2.0.1" }
pallet-sudo = { default-features = false, version = "2.0.1" }
frame-support = { default-features = false, version = "2.0.1" }
pallet-staking-reward-curve = { default-features = false, version = "2.0.1" }
frame-system = { default-features = false, version = "2.0.1" }
pallet-timestamp = { default-features = false, version = "2.0.1" }
pallet-tips = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment = { default-features = false, version = "2.0.1" }
pallet-treasury = { default-features = false, version = "2.0.1" }
pallet-utility = { default-features = false, version = "2.0.1" }

# substrate benchmark dependencies
frame-benchmarking = { default-features = false, version = "2.0.1", optional = true }
frame-system-benchmarking = { default-features = false, version = "2.0.1", optional = true }

# Used for the crust's RPCs
frame-system-rpc-runtime-api = { default-features = false, version = "2.0.1" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = "2.0.1" }

# crust runtime modules
balances = { version = "0.11.0", package = 'cstrml-balances', path = '../cstrml/balances', default-features = false }
candy = { version = "0.11.0", package = 'cstrml-candy', path = '../cstrml/candy', default-features = false  }
market = { version = "0.11.0", package = 'cstrml-market', path = '../cstrml/market', default-features = false }
primitives = { version = "0.11.0", package = 'cst-primitives', path = '../primitives', default-features = false }
swork = { version = "0.11.0", package = 'cstrml-swork', path = '../cstrml/swork', default-features = false }
swork-benchmarking = { version = "0.11.0", package = 'cstrml-swork-benchmarking', path = '../cstrml/swork/benchmarking', default-features = false, optional = true }
staking = { version = "0.11.0", package = 'cstrml-staking', path = '../cstrml/staking', default-features = false }

[features]
default = ['std']
std = [
    'authority-discovery-primitives/std',
    'babe-primitives/std',
    'codec/std',
    'primitives/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'frame-support/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-staking/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'pallet-authorship/std',
    'pallet-authority-discovery/std',
    'pallet-babe/std',
    'balances/std',
    'pallet-bounties/std',
    'candy/std',
    'pallet-collective/std',
    'pallet-elections-phragmen/std',
    'frame-executive/std',
    'pallet-democracy/std',
    'pallet-grandpa/std',
    'pallet-identity/std',
    'pallet-im-online/std',
    'pallet-indices/std',
    'market/std',
    'pallet-membership/std',
    'pallet-offences/std',
    'pallet-randomness-collective-flip/std',
    'pallet-scheduler/std',
    'pallet-session/std',
    'staking/std',
    'pallet-sudo/std',
    'swork/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-timestamp/std',
    'pallet-tips/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-treasury/std',
    'pallet-utility/std',
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "balances/runtime-benchmarks",
    "frame-system-benchmarking",
    "staking/runtime-benchmarks",
    "market/runtime-benchmarks",
    "swork-benchmarking"
]