[package]
authors = ['crustio']
edition = '2018'
name = 'crust-runtime'
version = '0.8.1'
build = 'build.rs'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[build-dependencies.wasm-builder-runner]
package = "substrate-wasm-builder-runner"
git = "https://github.com/paritytech/substrate"
branch = "rococo-branch" 

[dev-dependencies]
sp-io = { version = "2.0.0-rc6" }

[dependencies]
# third party dependencies
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '1.3.4' }
serde = { features = ['derive'], optional = true, version = '1.0.106' }
static_assertions = "1.1.0"

# substrate frame dependencies
authorship = { default-features = false, package = 'pallet-authorship', version = '2.0.0-rc6' }
authority-discovery = { default-features = false, package = 'pallet-authority-discovery', version = '2.0.0-rc6' }
babe = { default-features = false, package = 'pallet-babe', version = '2.0.0-rc6' }
collective = { default-features = false, package = 'pallet-collective', version = '2.0.0-rc6' }
frame-executive = { default-features = false, version = '2.0.0-rc6' }
frame-support = { default-features = false, version = "2.0.0-rc6" }
finality-tracker = { default-features = false, package = 'pallet-finality-tracker', version = '2.0.0-rc6' }
grandpa = { default-features = false, package = 'pallet-grandpa', version = '2.0.0-rc6' }
indices = { package = "pallet-indices", version = '2.0.0-rc6', default-features = false }
im-online = { default-features = false, package = 'pallet-im-online', version = '2.0.0-rc6' }
randomness-collective-flip = { default-features = false, package = 'pallet-randomness-collective-flip', version = '2.0.0-rc6' }
system = { default-features = false, package = 'frame-system', version = '2.0.0-rc6' }
session = { default-features = false, package = 'pallet-session', version = '2.0.0-rc6' }
pallet-staking-reward-curve = { default-features = false, version = '2.0.0-rc6' }
timestamp = { default-features = false, package = 'pallet-timestamp', version = '2.0.0-rc6' }
transaction-payment = { default-features = false, package = 'pallet-transaction-payment', version = '2.0.0-rc6' }
scheduler = { default-features = false, package = 'pallet-scheduler', version = '2.0.0-rc6' }
sudo = { default-features = false, package = 'pallet-sudo', version = '2.0.0-rc6' }
offences = { default-features = false, package = 'pallet-offences', version = '2.0.0-rc6' }
treasury = { default-features = false, package = 'pallet-treasury', version = '2.0.0-rc6' }
elections-phragmen = { default-features = false, package = 'pallet-elections-phragmen', version = '2.0.0-rc6' }
frame-benchmarking = { default-features = false, version = '2.0.0-rc6', optional = true }
frame-system-benchmarking = { default-features = false, version = '2.0.0-rc6', optional = true }

# Used for the crust's RPCs
frame-system-rpc-runtime-api = { default-features = false, version = '2.0.0-rc6' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = '2.0.0-rc6' }

# substrate primitives
authority-discovery-primitives = { default-features = false, package = 'sp-authority-discovery', version = '2.0.0-rc6' }
babe-primitives = { default-features = false, package = 'sp-consensus-babe', version = '0.8.0-rc6' }
sp-api = { default-features = false, version = '2.0.0-rc6' }
sp-block-builder = { default-features = false, version = '2.0.0-rc6' }
sp-core = { default-features = false, version = '2.0.0-rc6' }
sp-inherents = { default-features = false, version = '2.0.0-rc6' }
sp-io = { default-features = false, version = '2.0.0-rc6' }
sp-offchain = { default-features = false, version = '2.0.0-rc6' }
sp-runtime = { default-features = false, version = '2.0.0-rc6' }
sp-session = { default-features = false, version = '2.0.0-rc6' }
sp-staking = { default-features = false, version = '2.0.0-rc6' }
sp-std = { default-features = false, version = '2.0.0-rc6' }
sp-transaction-pool = { default-features = false, version = '2.0.0-rc6' }
sp-version = { default-features = false, version = '2.0.0-rc6' }
sp-runtime-interface = { default-features = false, version = '2.0.0-rc6' }

# crust runtime modules
swork = { package = 'cstrml-swork', path = '../cstrml/swork', default-features = false }
staking = { package = 'cstrml-staking', path = '../cstrml/staking', default-features = false }
market = { package = 'cstrml-market', path = '../cstrml/market', default-features = false }
payment = { package = 'cstrml-payment', path = '../cstrml/payment', default-features = false }
primitives = { package = 'cst-primitives', path = '../primitives', default-features = false }
balances = { default-features = false, package = 'cstrml-balances', path = '../cstrml/balances' }

# Cumulus dependencies
cumulus-runtime = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-parachain-upgrade = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-message-broker = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-upward-message = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-primitives = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-token-dealer = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }

parachain-info = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9'}
rococo-parachain-primitives = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9'}

# polkadot dependencies
rococo-runtime = { git = "https://github.com/paritytech/polkadot", default-features = false, rev = '93f0029184a6c1749ce9420f4df1628a313a117d' }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", default-features = false, rev = '93f0029184a6c1749ce9420f4df1628a313a117d' }

[features]
default = ['std']
no_std = []
std = [
    'authorship/std',
    'authority-discovery-primitives/std',
    'authority-discovery/std',
    'babe/std',
    'babe-primitives/std',
    'balances/std',
    'codec/std',
    'collective/std',
    'frame-executive/std',
    'frame-support/std',
    'grandpa/std',
    'finality-tracker/std',
    'im-online/std',
    'indices/std',
    'randomness-collective-flip/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-staking/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'sudo/std',
    'session/std',
    'system/std',
    'frame-system-rpc-runtime-api/std',
    'timestamp/std',
    'transaction-payment/std',
    'scheduler/std',
    'offences/std',
    'treasury/std',
    'elections-phragmen/std',
    'sp-runtime-interface/std',
    'swork/std',
    'staking/std',
    'market/std',
    'payment/std',
    'primitives/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    "cumulus-message-broker/std",
    "cumulus-parachain-upgrade/std",
    "cumulus-primitives/std",
    "cumulus-runtime/std",
    "cumulus-upward-message/std",
    "cumulus-token-dealer/std",
    "parachain-info/std",
    "rococo-parachain-primitives/std",
    "polkadot-parachain/std",
    "rococo-runtime/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "collective/runtime-benchmarks",
    "balances/runtime-benchmarks",
    "frame-system-benchmarking",
    "staking/runtime-benchmarks",
    "market/runtime-benchmarks",
    "swork/runtime-benchmarks",
]

disable-runtime-api = []

# Will be enabled by the `wasm-builder` when building the runtime for WASM.
runtime-wasm = [
    "cumulus-upward-message/runtime-wasm",
]