[package]
authors = ['crustio']
edition = '2018'
name = 'crust-runtime'
version = '0.8.1'
build = 'build.rs'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[build-dependencies.wasm-builder-runner]
package = "substrate-wasm-builder-runner"
version = "1.0.6"

[dependencies]
# third party dependencies
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '1.3.4' }
serde = { features = ['derive'], optional = true, version = '1.0.106' }
static_assertions = "1.1.0"

# substrate frame dependencies
authorship = { default-features = false, package = 'pallet-authorship',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
authority-discovery = { default-features = false, package = 'pallet-authority-discovery',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
babe = { default-features = false, package = 'pallet-babe',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
collective = { default-features = false, package = 'pallet-collective',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-executive = { default-features = false,  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-support = { default-features = false,  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
finality-tracker = { default-features = false, package = 'pallet-finality-tracker',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
grandpa = { default-features = false, package = 'pallet-grandpa',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
indices = { package = "pallet-indices",  git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
im-online = { default-features = false, package = 'pallet-im-online',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
randomness-collective-flip = { default-features = false, package = 'pallet-randomness-collective-flip',   git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
system = { default-features = false, package = 'frame-system',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
session = { default-features = false, package = 'pallet-session',   git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-staking-reward-curve = { default-features = false,   git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
timestamp = { default-features = false, package = 'pallet-timestamp',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
transaction-payment = { default-features = false, package = 'pallet-transaction-payment',  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
scheduler = { default-features = false, package = 'pallet-scheduler', git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sudo = { default-features = false, package = 'pallet-sudo', git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
offences = { default-features = false, package = 'pallet-offences', git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
treasury = { default-features = false, package = 'pallet-treasury', git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
elections-phragmen = { default-features = false, package = 'pallet-elections-phragmen', git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , optional = true }
frame-system-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , optional = true }

# Used for the crust's RPCs
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }

# substrate primitives
authority-discovery-primitives = { default-features = false, package = 'sp-authority-discovery', git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
babe-primitives = { default-features = false, package = 'sp-consensus-babe', git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-block-builder = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-inherents = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-offchain = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-session = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-staking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-transaction-pool = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-version = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }
sp-runtime-interface = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }

# crust runtime modules
swork = { package = 'cstrml-swork', path = '../cstrml/swork', default-features = false }
staking = { package = 'cstrml-staking', path = '../cstrml/staking', default-features = false }
market = { package = 'cstrml-market', path = '../cstrml/market', default-features = false }
payment = { package = 'cstrml-payment', path = '../cstrml/payment', default-features = false }
primitives = { package = 'cst-primitives', path = '../primitives', default-features = false }
balances = { default-features = false, package = 'cstrml-balances', path = '../cstrml/balances' }

# Cumulus dependencies
cumulus-runtime = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-parachain-upgrade = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-message-broker = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-upward-message = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-primitives = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
cumulus-token-dealer = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }
parachain-info = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '4e7f138c828bcf118df1c988a400d4dac8e904d9' }

[features]
default = ['std']
no_std = []
std = [
    'authorship/std',
    'authority-discovery-primitives/std',
    'authority-discovery/std',
    'babe/std',
    'babe-primitives/std',
    'balances/std',
    'codec/std',
    'collective/std',
    'frame-executive/std',
    'frame-support/std',
    'grandpa/std',
    'finality-tracker/std',
    'im-online/std',
    'indices/std',
    'randomness-collective-flip/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-staking/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'sudo/std',
    'session/std',
    'system/std',
    'frame-system-rpc-runtime-api/std',
    'timestamp/std',
    'transaction-payment/std',
    'scheduler/std',
    'offences/std',
    'treasury/std',
    'elections-phragmen/std',
    'sp-runtime-interface/std',
    'swork/std',
    'staking/std',
    'market/std',
    'payment/std',
    'primitives/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    "cumulus-message-broker/std",
    "cumulus-parachain-upgrade/std",
    "cumulus-primitives/std",
    "cumulus-runtime/std",
    "cumulus-upward-message/std",
    "cumulus-token-dealer/std",
    "parachain-info/std"
]

# Will be enabled by the `wasm-builder` when building the runtime for WASM.
runtime-wasm = [
    "cumulus-upward-message/runtime-wasm",
]