[package]
name = "cstrml-staking"
version = "0.8.1"
authors = ["crustio"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[dependencies]
# third party dependencies
serde = { version = "1.0.106", optional = true }
safe-mix = { version = "1.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }

# substrate frame dependencies
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-session = {  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-authorship = {  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }

# substrate primitives
sp-keyring = { optional = true,  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-std = {  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-io ={  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-runtime = {  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-staking = {  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
frame-benchmarking = {  git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" , optional = true }
rand_chacha = { version = "0.2", default-features = false }

# crust runtime modules
swork = { package = "cstrml-swork", path = "../swork", default-features = false }
primitives = { package = 'cst-primitives', path = '../../primitives', default-features = false }

[dev-dependencies]
sp-core= { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
balances = { package = 'cstrml-balances', path = '../balances' }
pallet-timestamp = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-benchmarking = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

# private crate inside substrate
substrate-test-utils = { version = '2.0.0-alpha.5', git = 'https://github.com/paritytech/substrate.git', rev = 'd1b9ccad107e4899978858de5ddd2868b9777aab'}

[features]
equalize = []
migrate = []
default = ["std", "equalize"]
std = [
	"serde",
	"safe-mix/std",
	"sp-keyring",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"primitives/std",
	"frame-system/std",
	"pallet-authorship/std",
	"swork/std"
]
runtime-benchmarks = [
    "frame-benchmarking",
]