[package]
name = "cstrml-candy"
version = "0.8.1"
authors = ["crustio"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }

# substrate pallet dependency
pallet-assets = { default-features = false, version = '2.0.0-rc6' }

# substrate frame dependencies
frame-support = { default-features = false, version = '2.0.0-rc6' }
frame-system = { default-features = false, version = '2.0.0-rc6' }

[features]
default = ["std"]
std = [
    "codec/std",
    "pallet-assets/std",
    "frame-support/std",
    "frame-system/std",
]