[package]
name = "cstrml-candy"
version = "0.8.2"
authors = ["crustio"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[dependencies]
serde = { version = "1.0.106", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }

# Substrate frame dependencies
frame-support = { default-features = false, version = '2.0.0-rc6' }
frame-system = { default-features = false, version = '2.0.0-rc6' }
sp-runtime = { default-features = false, version = '2.0.0-rc6' }

[dev-dependencies]
sp-core = '2.0.0-rc6'
sp-std = '2.0.0-rc6'
sp-io = '2.0.0-rc6'

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
]