[package]
name = 'crust'
version = '0.10.0'
authors = ['crustio']
build = 'build.rs'
edition = '2018'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[[bin]]
name = 'crust'

[dependencies]
# third parity dependencies
futures = "0.3.4"
log = "0.4.8"
structopt = { version = '0.3.8', optional = true }
hex-literal = "0.2.1"
serde = { version = "1.0.116", features = ["derive"] }
jsonrpc-core = "15.1.0"
jsonrpc-pubsub = "14.2.0"
codec = { package = "parity-scale-codec", version = "1.3.4" }

# substrate client dependencies
authority-discovery = { package = 'sc-authority-discovery', git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-finality-grandpa  = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-cli = {  git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"], optional = true }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-executor = {  git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = {  git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"] }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# substrate primitives
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# Cumulus dependencies
cumulus-consensus = { git = "https://github.com/MyronFanQiu/cumulus", default-features = false, branch = "rococo-v1" }
cumulus-collator = { git = "https://github.com/MyronFanQiu/cumulus", default-features = false, branch = "rococo-v1" }
cumulus-network = { git = "https://github.com/MyronFanQiu/cumulus", default-features = false, branch = "rococo-v1" }
cumulus-primitives = { git = "https://github.com/MyronFanQiu/cumulus", default-features = false, branch = "rococo-v1" }
cumulus-service = { git = "https://github.com/MyronFanQiu/cumulus", default-features = false, branch = "rococo-v1" }

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }

sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-trie = { default-features = false, git = "https://github.com/paritytech/substrate", features = ["memory-tracker"], branch = "rococo-v1" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
node-inspect = { optional = true, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# crust runtime modules
crust-runtime = { path = '../runtime', version = '0.10.0' }
cstrml-staking = { path = '../cstrml/staking', version = '0.10.0' }
cstrml-swork = { path = '../cstrml/swork', version = '0.10.0' }
primitives = { package = 'cst-primitives', path = '../primitives', version = '0.10.0' }
crust-rpc = { path =  '../rpc', version = '0.10.0' }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

[build-dependencies]
build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1",  package = "substrate-build-script-utils", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
node-inspect = { optional = true, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

[features]
default = [ "cli" ]
cli = [
    "wasmi-errno",
    "sc-cli",
    "frame-benchmarking-cli",
    "sc-service/db",
    "structopt",
    "build-script-utils",
    "polkadot-cli",
    "node-inspect",
]

runtime-benchmarks = [
    "crust-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
]

wasmtime = [
    "sc-executor/wasmtime",
]

wasmi-errno = [
    "sc-executor/wasmi-errno",
]