[package]
name = 'crust'
version = '0.11.0'
authors = ['crustio']
build = 'build.rs'
edition = '2018'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[[bin]]
name = 'crust'

[dependencies]
# third parity dependencies
futures = "0.3.8"
log = "0.4.11"
structopt = { version = '0.3.21', optional = true }
hex-literal = "0.3.1"

# substrate client dependencies
authority-discovery = { package = 'sc-authority-discovery', version = "0.8.1" }
sc-consensus-babe = "0.8.1"
sc-finality-grandpa  = "0.8.1"
sc-basic-authorship = "0.8.1"
sc-client-api = "2.0.1"
sc-cli = {  version = "0.8.1", features = ["wasmtime"], optional = true }
sc-consensus = "0.8.1"
sc-consensus-slots = "0.8.1"
sc-executor = {  version = "0.8.1", features = ["wasmtime"] }
sc-network = "0.8.1"
sc-service = {  version = "0.8.1", features = ["wasmtime"] }
sc-transaction-pool = "2.0.1"

# substrate primitives
sp-transaction-pool = "2.0.1"
sp-core = "2.0.1"
sp-consensus = "0.8.1"
sp-consensus-babe = "0.8.1"
sp-inherents = "2.0.1"
sp-io = "2.0.1"
sp-runtime = "2.0.1"
sp-finality-grandpa = "2.0.1"
frame-benchmarking-cli = { version = "2.0.1", optional = true }
frame-benchmarking = "2.0.1"

# crust runtime modules
crust-runtime = { path = '../runtime', version = '0.11.0' }
cstrml-staking = { path = '../cstrml/staking', version = '0.11.0' }
cstrml-swork = { path = '../cstrml/swork', version = '0.11.0' }
primitives = { package = 'cst-primitives', path = '../primitives', version = '0.11.0' }
crust-rpc = { path =  '../rpc', version = '0.11.0' }

[build-dependencies]
substrate-build-script-utils = "2.0.1"

[features]
default = [ "cli" ]
cli = [
    "wasmi-errno",
    "sc-cli",
    "frame-benchmarking-cli",
    "sc-service/db",
    "structopt",
]

runtime-benchmarks = [
    "crust-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
]

wasmtime = [
    "sc-executor/wasmtime",
]

wasmi-errno = [
    "sc-executor/wasmi-errno",
]