[package]
name = 'crust'
version = '0.8.1'
authors = ['crustio']
build = 'build.rs'
edition = '2018'
license = "GPL-3.0"
homepage = "https://crust.network"
repository = "https://github.com/crustio/crust/"

[[bin]]
name = 'crust'

[dependencies]
# third parity dependencies
futures = "0.3.4"
log = "0.4.8"
structopt = { version = '0.3.8', optional = true }
hex-literal = "0.2.1"

# substrate client dependencies
babe = { version = "0.8.0-rc6", package = 'sc-consensus-babe' }
grandpa = { version = "0.8.0-rc6", package = "sc-finality-grandpa" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package= 'sc-authority-discovery' }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", features = ["wasmtime"], optional = true }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", features = ["wasmtime"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
service = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sc-service", features = ["wasmtime"] }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

# substrate primitives
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-consensus = { version = "0.8.0-rc6" }
sp-consensus-babe = { version = "0.8.0-rc6" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
grandpa-primitives = { package = 'sp-finality-grandpa', git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

# crust runtime modules
crust-runtime = { path = '../runtime', version = '0.8.1' }
cstrml-staking = { path = '../cstrml/staking', version = '0.8.1' }
cstrml-swork = { path = '../cstrml/swork', version = '0.8.1' }
primitives = { package = 'cst-primitives', path = '../primitives', version = '0.8.1' }
crust-rpc = { path =  '../rpc', version = '0.8.1' }

# cumulus dependencies
cumulus-primitives = { git = "https://github.com/paritytech/cumulus" }
cumulus-network = { git = "https://github.com/paritytech/cumulus" }
cumulus-service = { git = "https://github.com/paritytech/cumulus" }
cumulus-consensus = { git = "https://github.com/paritytech/cumulus" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }
polkadot-collator = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }

[build-dependencies]
build-script-utils = {  git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "substrate-build-script-utils", optional = true }
frame-benchmarking-cli = { optional = true,  git = "https://github.com/paritytech/substrate", branch = "rococo-branch"  }

[features]
default = [ "cli" ]
cli = [
    "wasmi-errno",
    "sc-cli",
    "frame-benchmarking-cli",
    "service/db",
    "structopt",
    "build-script-utils",
]

runtime-benchmarks = [
    "crust-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
]

wasmtime = [
    "sc-executor/wasmtime",
]

wasmi-errno = [
    "sc-executor/wasmi-errno",
]